phrase:
  access_token: 91d35b928fea76c4b360ca3fcb9505f8972623fd9b0f2f43d1f0457b0a8f6dc5
  project_id: fb5f347a0581a14f8517bd01c86ecb23
  file format: xml
  
  
  push:
    sources:
    - file: ./source-locale/main/figma-designs/design_keys.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: false
        
        
  pull:
    targets:
    - file: ./translations/de/design_keys.xml
      params: 
        locale_id: de
        file_format: xml
    - file: ./translations/el/design_keys.xml
      params: 
        locale_id: el
        file_format: xml
    - file: ./translations/es/design_keys.xml
      params: 
        locale_id: es
        file_format: xml
